In [1]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [2]:
b=a[2:4,0:2]
print(b)

[[11 12]
 [16 17]]


In [3]:
c=a.diagonal(offset=1)
c

array([ 2,  8, 14, 20])

In [4]:
d=a[[0,4,5],3:5]
d

array([[ 4,  5],
       [24, 25],
       [29, 30]])